/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorTemplates from "./GovernorTemplates";
export type { governorTemplates };
import type * as timeLocks from "./TimeLocks";
export type { timeLocks };
import type * as voteTokens from "./VoteTokens";
export type { voteTokens };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { GovernorFactory } from "./GovernorFactory";
