/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as privateSaleSol from "./PrivateSale.sol";
export type { privateSaleSol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
