/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITimelockControllerInitilizer,
  ITimelockControllerInitilizerInterface,
} from "../../../contracts/interfaces/ITimelockControllerInitilizer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "minDelay",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "proposers",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "executors",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "admin",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITimelockControllerInitilizer__factory {
  static readonly abi = _abi;
  static createInterface(): ITimelockControllerInitilizerInterface {
    return new utils.Interface(_abi) as ITimelockControllerInitilizerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITimelockControllerInitilizer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITimelockControllerInitilizer;
  }
}
