/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governorTemplates from "./GovernorTemplates";
export * as timeLocks from "./TimeLocks";
export * as voteTokens from "./VoteTokens";
export * as interfaces from "./interfaces";
export { GovernorFactory__factory } from "./GovernorFactory__factory";
